### PR TITLE
Improve jena observability module (#13)

### PR DESCRIPTION
**Pull request by dptelicent**
Not sure if the below is needed just once or for each test (as currently)?

        JenaSystem.init();
        FusekiLogging.setLogging();
        FusekiModule module = new FMod_OpenTelemetry();
        FusekiModules.add(module);

### CODE REVIEW

**Comment by afs** [comment]
Running the builld (`mvn clean install -Pdev`) I get a RAT note of an archive:

jena-fuseki2/jena-fuseki-main/agents/opentelemetry-javaagent.jar

but don't see this file. Does it come and go in a build?

**Review by afs — CHANGES_REQUESTED** [review]

**Comment by dptelicent** [comment]
No I put it there manually from here:

https://opentelemetry.io/docs/instrumentation/java/automatic/


I assumed JARs shouldn't be committed to Git.
________________________________

**Comment by dptelicent** [comment]
I can't see an agents folder or file here...

https://github.com/Telicent-io/jena/tree/13-improve-jena-observability-module/jena-fuseki2/jena-fuseki-main
________________________________

**Comment by dptelicent** [comment]
All above issues now addressed.

**Pull request merged**
